name: deploy-gh-pages
on:
    push:
        branches:
        - nextjs
jobs:
    build:

        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                node-version: 12.x
            - name: npm install, build, export
              run: |
                npm install
                npm run build
                npm run export
                touch out/.nojekyll

            - name: Deploy
              uses: s0/git-publish-subdir-action@develop
              env:
                REPO: self
                BRANCH: gh-pages
                FOLDER: out
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
