name: deploy-gh-pages
on:
  workflow_dispatch:
  push:
    branches:
      - nextjs
  repository_dispatch:
    types: [resume-event]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: npm install, build, export
        env:
          PAT: ${{ secrets.pat }}
        run: |
          npm install
          npm run build
          npm run export
          touch out/.nojekyll

      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: out
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
